plugins {
    id 'java'
    id 'maven-publish'
}

group = 'vn.haohan'
version = providers.gradleProperty('projectVersion').orElse('1.0.0').get()

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:${property('paperVersion')}")
    testImplementation("io.papermc.paper:paper-api:${property('paperVersion')}")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    filesMatching('paper-plugin.yml') {
        expand(project: [version: project.version])
    }
}

jar {
    archiveBaseName = project.name
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'HaoHanItemCore'
        }
    }
}
